blockchain:
  url: https://sepolia.infura.io/v3/4acf1231e76946a59e2f3c2cfc8ce3db
  private_key: 395830046eff7441b17791163c7690f457dbe2ea7b4d46ca33dc50b60f6725e3
  gas_limit: 10000000
  gas_price: 4000000000
  default_wei_founds: 0

grpc:
  ip: 0.0.0.0
  port: 30000

postgresql:
  username: postgres
  password: postgres
  database: voting-manager
  host: localhost
  port: 5432