blockchain:
  url: http://127.0.0.1:8545
  private_key: 944f026eec56fe79aeec1a281eef0630a2d03528dba2a5f7ed968cab915b011c
  gas_limit: 10000000
  gas_price: 2000000000
  default_wei_founds: 0

grpc:
  ip: 0.0.0.0
  port: 30000

postgresql:
  username: postgres
  password: postgres
  database: voting-manager
  host: localhost
  port: 5432