grpc:
  ip: 0.0.0.0
  port: 30003

postgresql:
  username: postgres
  password: postgres
  database: app
  host: localhost
  port: 5433

http:
  ip: 0.0.0.0
  port: 30002

voting-manager-grpc:
  ip: 0.0.0.0
  port: 30000